version: "3.9"

services:
    db:
        image: "postgres:15"
        container_name: "zapier_db"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
